# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: continuumio/anaconda3

pipelines:
  default:
    - step:
        caches:
          - condacache
        script: # Modify the commands below to build your repository.
          - conda update -y conda
          - conda env list
          - conda env update --file linux_environment.yml
          - pip install -e .
          - pip install pytest
          - pytest

definitions:
  caches:
    condacache: /opt/python/bin