# Bitbucket build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

definitions:
  caches:
    poetry-path: /root/.poetry
    poetry-venv: /root/.cache/pypoetry/virtualenvs

pipelines:
  default:
    - step:
        name: test-3.7
        services:
          - docker
        image: python:3.7
        caches:
          - poetry-path
          - poetry-venv
        script:
          - pip install poetry
          - apt-get -y install gcc
          - poetry install -E "test keyring"
          - export PYTHONPATH=.
          - poetry run python -m unittest discover -s tests -b -v

    - step:
        name: test-3.8
        services:
          - docker
        image: python:3.8
        caches:
          - poetry-path
          - poetry-venv
        script:
          - pip install poetry
          - apt-get -y install gcc
          - poetry install -E "test keyring"
          - export PYTHONPATH=.
          - poetry run python -m unittest discover -s tests -b -v
