name: bi_etl37
channels:
  - esri
  - defaults
dependencies:
  - python>=3.7
  - gevent
  - ipython
  - keyring
  - SQLAlchemy
  - psutil
  - pywin32
  - pytest
  - pip:
    - btrees
    - semidbm
    - sortedcontainers
    - openpyxl
    - CaseInsensitiveDict
    - sphinx
    - sphinx-autodoc-annotation
    - slackclient
