name: base
channels:
  - defaults
dependencies:
  - python>=3.7
  - gevent
  - SQLAlchemy
  - psutil
  - keyring
  - pytest
  - pip:
    - btrees
    - semidbm
    - sortedcontainers
    - openpyxl
    - CaseInsensitiveDict
    - slackclient
