from tests.db_base_tests.base_test_hst_table_source_based import BaseTestHistoryTableSourceBased


class TestHistoryTableSourceBasedSqlite(BaseTestHistoryTableSourceBased):
    pass

del BaseTestHistoryTableSourceBased
